2017-10-24 17:40:04 [18060] [INFO] Starting gunicorn 19.1.0
2017-10-24 17:40:04 [18060] [INFO] Listening at: http://0.0.0.0:8000 (18060)
2017-10-24 17:40:04 [18060] [INFO] Using worker: sync
2017-10-24 17:40:04 [18063] [INFO] Booting worker with pid: 18063
2017-10-24 17:40:04 [18064] [INFO] Booting worker with pid: 18064
2017-10-24 17:40:04 [18065] [INFO] Booting worker with pid: 18065
2017-10-24 17:40:04 [18066] [INFO] Booting worker with pid: 18066
2017-10-24 17:40:04 [18060] [INFO] 4 workers
2017-10-24 17:40:21 [18064] [INFO] Worker exiting (pid: 18064)
2017-10-24 17:40:21 [18065] [INFO] Worker exiting (pid: 18065)
2017-10-24 17:40:21 [18066] [INFO] Worker exiting (pid: 18066)
2017-10-24 17:40:21 [18063] [INFO] Worker exiting (pid: 18063)
2017-10-24 17:40:21 [18060] [INFO] 4 workers
2017-10-24 17:40:21 [18060] [INFO] Handling signal: int
2017-10-24 17:40:22 [18060] [INFO] Shutting down: Master
2017-10-24 17:41:12 [18268] [INFO] Starting gunicorn 19.1.0
2017-10-24 17:41:12 [18268] [INFO] Listening at: http://0.0.0.0:8000 (18268)
2017-10-24 17:41:12 [18268] [INFO] Using worker: sync
2017-10-24 17:41:12 [18271] [INFO] Booting worker with pid: 18271
2017-10-24 17:41:12 [18272] [INFO] Booting worker with pid: 18272
2017-10-24 17:41:12 [18273] [INFO] Booting worker with pid: 18273
2017-10-24 17:41:12 [18274] [INFO] Booting worker with pid: 18274
2017-10-24 17:41:13 [18268] [INFO] 4 workers
2017-10-24 17:41:17 [18268] [INFO] 4 workers
2017-10-24 17:41:17 [18268] [INFO] Handling signal: int
2017-10-24 17:41:17 [18272] [INFO] Worker exiting (pid: 18272)
2017-10-24 17:41:17 [18268] [INFO] Shutting down: Master
2017-10-24 19:18:38 [23063] [INFO] Starting gunicorn 19.1.0
2017-10-24 19:18:38 [23063] [INFO] Listening at: http://0.0.0.0:8000 (23063)
2017-10-24 19:18:38 [23063] [INFO] Using worker: sync
2017-10-24 19:18:38 [23066] [INFO] Booting worker with pid: 23066
2017-10-24 19:18:38 [23067] [INFO] Booting worker with pid: 23067
2017-10-24 19:18:39 [23068] [INFO] Booting worker with pid: 23068
2017-10-24 19:18:39 [23069] [INFO] Booting worker with pid: 23069
2017-10-24 19:18:39 [23063] [INFO] 4 workers
2017-10-24 19:19:08 [23063] [INFO] 4 workers
2017-10-24 19:19:17 [23069] [INFO] Worker exiting (pid: 23069)
2017-10-24 19:19:17 [23066] [INFO] Worker exiting (pid: 23066)
2017-10-24 19:19:17 [23068] [INFO] Worker exiting (pid: 23068)
2017-10-24 19:19:17 [23067] [INFO] Worker exiting (pid: 23067)
2017-10-24 19:19:17 [23063] [INFO] 4 workers
2017-10-24 19:19:17 [23063] [INFO] Handling signal: int
2017-10-24 19:19:18 [23063] [INFO] Shutting down: Master
2017-10-24 19:19:25 [23161] [INFO] Starting gunicorn 19.1.0
2017-10-24 19:19:25 [23161] [INFO] Listening at: http://0.0.0.0:8000 (23161)
2017-10-24 19:19:25 [23161] [INFO] Using worker: sync
2017-10-24 19:19:25 [23164] [INFO] Booting worker with pid: 23164
2017-10-24 19:19:25 [23165] [INFO] Booting worker with pid: 23165
2017-10-24 19:19:25 [23166] [INFO] Booting worker with pid: 23166
2017-10-24 19:19:25 [23167] [INFO] Booting worker with pid: 23167
2017-10-24 19:19:25 [23161] [INFO] 4 workers
2017-10-24 19:19:55 [23161] [INFO] 4 workers
2017-10-24 19:20:11 [23161] [INFO] 4 workers
2017-10-24 19:20:26 [23161] [INFO] 4 workers
2017-10-24 19:20:32 [23164] [INFO] Worker exiting (pid: 23164)
2017-10-24 19:20:32 [23166] [INFO] Worker exiting (pid: 23166)
2017-10-24 19:20:32 [23167] [INFO] Worker exiting (pid: 23167)
2017-10-24 19:20:32 [23165] [INFO] Worker exiting (pid: 23165)
2017-10-24 19:20:32 [23161] [INFO] 4 workers
2017-10-24 19:20:32 [23161] [INFO] Handling signal: int
2017-10-24 19:20:32 [23161] [INFO] Shutting down: Master
2017-10-24 19:20:58 [23527] [INFO] Starting gunicorn 19.1.0
2017-10-24 19:20:58 [23527] [INFO] Listening at: http://0.0.0.0:8000 (23527)
2017-10-24 19:20:58 [23527] [INFO] Using worker: sync
2017-10-24 19:20:58 [23531] [INFO] Booting worker with pid: 23531
2017-10-24 19:20:58 [23532] [INFO] Booting worker with pid: 23532
2017-10-24 19:20:58 [23533] [INFO] Booting worker with pid: 23533
2017-10-24 19:20:58 [23534] [INFO] Booting worker with pid: 23534
2017-10-24 19:20:58 [23527] [INFO] 4 workers
2017-10-24 19:21:19 [23531] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/gunicorn-19.1.0-py3.6.egg/gunicorn/workers/sync.py", line 93, in handle
    self.handle_request(listener, req, client, addr)
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/gunicorn-19.1.0-py3.6.egg/gunicorn/workers/sync.py", line 134, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
TypeError: startup() takes 0 positional arguments but 2 were given
2017-10-24 19:21:20 [23533] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/gunicorn-19.1.0-py3.6.egg/gunicorn/workers/sync.py", line 93, in handle
    self.handle_request(listener, req, client, addr)
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/gunicorn-19.1.0-py3.6.egg/gunicorn/workers/sync.py", line 134, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
TypeError: startup() takes 0 positional arguments but 2 were given
2017-10-24 19:21:28 [23527] [INFO] 4 workers
2017-10-24 19:21:49 [23527] [INFO] 4 workers
2017-10-24 19:22:04 [23527] [INFO] 4 workers
2017-10-24 19:22:19 [23527] [INFO] 4 workers
2017-10-24 19:22:34 [23527] [INFO] 4 workers
2017-10-24 19:22:49 [23527] [INFO] 4 workers
2017-10-24 19:22:59 [23533] [INFO] Worker exiting (pid: 23533)
2017-10-24 19:22:59 [23531] [INFO] Worker exiting (pid: 23531)
2017-10-24 19:22:59 [23534] [INFO] Worker exiting (pid: 23534)
2017-10-24 19:22:59 [23527] [INFO] 4 workers
2017-10-24 19:22:59 [23527] [INFO] Handling signal: int
2017-10-24 19:23:00 [23527] [INFO] Shutting down: Master
2017-10-24 19:23:05 [23692] [INFO] Starting gunicorn 19.1.0
2017-10-24 19:23:05 [23692] [INFO] Listening at: http://0.0.0.0:8000 (23692)
2017-10-24 19:23:05 [23692] [INFO] Using worker: sync
2017-10-24 19:23:05 [23695] [INFO] Booting worker with pid: 23695
2017-10-24 19:23:05 [23696] [INFO] Booting worker with pid: 23696
2017-10-24 19:23:05 [23697] [INFO] Booting worker with pid: 23697
2017-10-24 19:23:05 [23698] [INFO] Booting worker with pid: 23698
2017-10-24 19:23:05 [23692] [INFO] 4 workers
2017-10-24 19:23:10 [23698] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/gunicorn-19.1.0-py3.6.egg/gunicorn/arbiter.py", line 507, in spawn_worker
    worker.init_process()
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/gunicorn-19.1.0-py3.6.egg/gunicorn/workers/base.py", line 114, in init_process
    self.wsgi = self.app.wsgi()
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/gunicorn-19.1.0-py3.6.egg/gunicorn/app/base.py", line 66, in wsgi
    self.callable = self.load()
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/gunicorn-19.1.0-py3.6.egg/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/gunicorn-19.1.0-py3.6.egg/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/gunicorn-19.1.0-py3.6.egg/gunicorn/util.py", line 367, in import_app
    app = eval(obj, mod.__dict__)
  File "<string>", line 1, in <module>
  File "/home/xmn/dev/FluVigilanciaBR/fludashboard/fludashboard/app.py", line 42, in startup
    debug=settings.APP_DEBUG
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/flask/app.py", line 841, in run
    run_simple(host, port, self, **options)
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/werkzeug/serving.py", line 720, in run_simple
    s.bind((hostname, port))
OSError: [Errno 98] Address already in use
Traceback (most recent call last):
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/gunicorn-19.1.0-py3.6.egg/gunicorn/arbiter.py", line 507, in spawn_worker
    worker.init_process()
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/gunicorn-19.1.0-py3.6.egg/gunicorn/workers/base.py", line 114, in init_process
    self.wsgi = self.app.wsgi()
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/gunicorn-19.1.0-py3.6.egg/gunicorn/app/base.py", line 66, in wsgi
    self.callable = self.load()
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/gunicorn-19.1.0-py3.6.egg/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/gunicorn-19.1.0-py3.6.egg/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/gunicorn-19.1.0-py3.6.egg/gunicorn/util.py", line 367, in import_app
    app = eval(obj, mod.__dict__)
  File "<string>", line 1, in <module>
  File "/home/xmn/dev/FluVigilanciaBR/fludashboard/fludashboard/app.py", line 42, in startup
    debug=settings.APP_DEBUG
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/flask/app.py", line 841, in run
    run_simple(host, port, self, **options)
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/werkzeug/serving.py", line 720, in run_simple
    s.bind((hostname, port))
OSError: [Errno 98] Address already in use
2017-10-24 19:23:10 [23696] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/gunicorn-19.1.0-py3.6.egg/gunicorn/arbiter.py", line 507, in spawn_worker
    worker.init_process()
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/gunicorn-19.1.0-py3.6.egg/gunicorn/workers/base.py", line 114, in init_process
    self.wsgi = self.app.wsgi()
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/gunicorn-19.1.0-py3.6.egg/gunicorn/app/base.py", line 66, in wsgi
    self.callable = self.load()
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/gunicorn-19.1.0-py3.6.egg/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/gunicorn-19.1.0-py3.6.egg/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/gunicorn-19.1.0-py3.6.egg/gunicorn/util.py", line 367, in import_app
    app = eval(obj, mod.__dict__)
  File "<string>", line 1, in <module>
  File "/home/xmn/dev/FluVigilanciaBR/fludashboard/fludashboard/app.py", line 42, in startup
    debug=settings.APP_DEBUG
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/flask/app.py", line 841, in run
    run_simple(host, port, self, **options)
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/werkzeug/serving.py", line 720, in run_simple
    s.bind((hostname, port))
OSError: [Errno 98] Address already in use
Traceback (most recent call last):
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/gunicorn-19.1.0-py3.6.egg/gunicorn/arbiter.py", line 507, in spawn_worker
    worker.init_process()
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/gunicorn-19.1.0-py3.6.egg/gunicorn/workers/base.py", line 114, in init_process
    self.wsgi = self.app.wsgi()
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/gunicorn-19.1.0-py3.6.egg/gunicorn/app/base.py", line 66, in wsgi
    self.callable = self.load()
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/gunicorn-19.1.0-py3.6.egg/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/gunicorn-19.1.0-py3.6.egg/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/gunicorn-19.1.0-py3.6.egg/gunicorn/util.py", line 367, in import_app
    app = eval(obj, mod.__dict__)
  File "<string>", line 1, in <module>
  File "/home/xmn/dev/FluVigilanciaBR/fludashboard/fludashboard/app.py", line 42, in startup
    debug=settings.APP_DEBUG
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/flask/app.py", line 841, in run
    run_simple(host, port, self, **options)
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/werkzeug/serving.py", line 720, in run_simple
    s.bind((hostname, port))
OSError: [Errno 98] Address already in use
2017-10-24 19:23:10 [23696] [INFO] Worker exiting (pid: 23696)
2017-10-24 19:23:10 [23698] [INFO] Worker exiting (pid: 23698)
2017-10-24 19:23:10 [23695] [INFO] Worker exiting (pid: 23695)
2017-10-24 19:23:19 [23697] [INFO] Worker exiting (pid: 23697)
2017-10-24 19:23:19 [23692] [INFO] Shutting down: Master
2017-10-24 19:23:19 [23692] [INFO] Reason: Worker failed to boot.
2017-10-24 19:23:29 [23800] [INFO] Starting gunicorn 19.1.0
2017-10-24 19:23:29 [23800] [INFO] Listening at: http://0.0.0.0:8000 (23800)
2017-10-24 19:23:29 [23800] [INFO] Using worker: sync
2017-10-24 19:23:29 [23803] [INFO] Booting worker with pid: 23803
2017-10-24 19:23:29 [23804] [INFO] Booting worker with pid: 23804
2017-10-24 19:23:29 [23805] [INFO] Booting worker with pid: 23805
2017-10-24 19:23:29 [23806] [INFO] Booting worker with pid: 23806
2017-10-24 19:23:29 [23800] [INFO] 4 workers
2017-10-24 19:23:31 [23804] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/gunicorn-19.1.0-py3.6.egg/gunicorn/arbiter.py", line 507, in spawn_worker
    worker.init_process()
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/gunicorn-19.1.0-py3.6.egg/gunicorn/workers/base.py", line 114, in init_process
    self.wsgi = self.app.wsgi()
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/gunicorn-19.1.0-py3.6.egg/gunicorn/app/base.py", line 66, in wsgi
    self.callable = self.load()
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/gunicorn-19.1.0-py3.6.egg/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/gunicorn-19.1.0-py3.6.egg/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/gunicorn-19.1.0-py3.6.egg/gunicorn/util.py", line 367, in import_app
    app = eval(obj, mod.__dict__)
  File "<string>", line 1, in <module>
  File "/home/xmn/dev/FluVigilanciaBR/fludashboard/fludashboard/app.py", line 42, in startup
    debug=settings.APP_DEBUG
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/flask/app.py", line 841, in run
    run_simple(host, port, self, **options)
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/werkzeug/serving.py", line 720, in run_simple
    s.bind((hostname, port))
OSError: [Errno 98] Address already in use
Traceback (most recent call last):
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/gunicorn-19.1.0-py3.6.egg/gunicorn/arbiter.py", line 507, in spawn_worker
    worker.init_process()
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/gunicorn-19.1.0-py3.6.egg/gunicorn/workers/base.py", line 114, in init_process
    self.wsgi = self.app.wsgi()
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/gunicorn-19.1.0-py3.6.egg/gunicorn/app/base.py", line 66, in wsgi
    self.callable = self.load()
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/gunicorn-19.1.0-py3.6.egg/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/gunicorn-19.1.0-py3.6.egg/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/gunicorn-19.1.0-py3.6.egg/gunicorn/util.py", line 367, in import_app
    app = eval(obj, mod.__dict__)
  File "<string>", line 1, in <module>
  File "/home/xmn/dev/FluVigilanciaBR/fludashboard/fludashboard/app.py", line 42, in startup
    debug=settings.APP_DEBUG
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/flask/app.py", line 841, in run
    run_simple(host, port, self, **options)
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/werkzeug/serving.py", line 720, in run_simple
    s.bind((hostname, port))
OSError: [Errno 98] Address already in use
2017-10-24 19:23:31 [23804] [INFO] Worker exiting (pid: 23804)
2017-10-24 19:23:31 [23805] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/gunicorn-19.1.0-py3.6.egg/gunicorn/arbiter.py", line 507, in spawn_worker
    worker.init_process()
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/gunicorn-19.1.0-py3.6.egg/gunicorn/workers/base.py", line 114, in init_process
    self.wsgi = self.app.wsgi()
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/gunicorn-19.1.0-py3.6.egg/gunicorn/app/base.py", line 66, in wsgi
    self.callable = self.load()
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/gunicorn-19.1.0-py3.6.egg/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/gunicorn-19.1.0-py3.6.egg/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/gunicorn-19.1.0-py3.6.egg/gunicorn/util.py", line 367, in import_app
    app = eval(obj, mod.__dict__)
  File "<string>", line 1, in <module>
  File "/home/xmn/dev/FluVigilanciaBR/fludashboard/fludashboard/app.py", line 42, in startup
    debug=settings.APP_DEBUG
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/flask/app.py", line 841, in run
    run_simple(host, port, self, **options)
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/werkzeug/serving.py", line 720, in run_simple
    s.bind((hostname, port))
OSError: [Errno 98] Address already in use
Traceback (most recent call last):
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/gunicorn-19.1.0-py3.6.egg/gunicorn/arbiter.py", line 507, in spawn_worker
    worker.init_process()
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/gunicorn-19.1.0-py3.6.egg/gunicorn/workers/base.py", line 114, in init_process
    self.wsgi = self.app.wsgi()
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/gunicorn-19.1.0-py3.6.egg/gunicorn/app/base.py", line 66, in wsgi
    self.callable = self.load()
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/gunicorn-19.1.0-py3.6.egg/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/gunicorn-19.1.0-py3.6.egg/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/gunicorn-19.1.0-py3.6.egg/gunicorn/util.py", line 367, in import_app
    app = eval(obj, mod.__dict__)
  File "<string>", line 1, in <module>
  File "/home/xmn/dev/FluVigilanciaBR/fludashboard/fludashboard/app.py", line 42, in startup
    debug=settings.APP_DEBUG
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/flask/app.py", line 841, in run
    run_simple(host, port, self, **options)
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/werkzeug/serving.py", line 720, in run_simple
    s.bind((hostname, port))
OSError: [Errno 98] Address already in use
2017-10-24 19:23:31 [23805] [INFO] Worker exiting (pid: 23805)
2017-10-24 19:23:31 [23806] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/gunicorn-19.1.0-py3.6.egg/gunicorn/arbiter.py", line 507, in spawn_worker
    worker.init_process()
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/gunicorn-19.1.0-py3.6.egg/gunicorn/workers/base.py", line 114, in init_process
    self.wsgi = self.app.wsgi()
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/gunicorn-19.1.0-py3.6.egg/gunicorn/app/base.py", line 66, in wsgi
    self.callable = self.load()
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/gunicorn-19.1.0-py3.6.egg/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/gunicorn-19.1.0-py3.6.egg/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/gunicorn-19.1.0-py3.6.egg/gunicorn/util.py", line 367, in import_app
    app = eval(obj, mod.__dict__)
  File "<string>", line 1, in <module>
  File "/home/xmn/dev/FluVigilanciaBR/fludashboard/fludashboard/app.py", line 42, in startup
    debug=settings.APP_DEBUG
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/flask/app.py", line 841, in run
    run_simple(host, port, self, **options)
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/werkzeug/serving.py", line 720, in run_simple
    s.bind((hostname, port))
OSError: [Errno 98] Address already in use
Traceback (most recent call last):
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/gunicorn-19.1.0-py3.6.egg/gunicorn/arbiter.py", line 507, in spawn_worker
    worker.init_process()
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/gunicorn-19.1.0-py3.6.egg/gunicorn/workers/base.py", line 114, in init_process
    self.wsgi = self.app.wsgi()
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/gunicorn-19.1.0-py3.6.egg/gunicorn/app/base.py", line 66, in wsgi
    self.callable = self.load()
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/gunicorn-19.1.0-py3.6.egg/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/gunicorn-19.1.0-py3.6.egg/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/gunicorn-19.1.0-py3.6.egg/gunicorn/util.py", line 367, in import_app
    app = eval(obj, mod.__dict__)
  File "<string>", line 1, in <module>
  File "/home/xmn/dev/FluVigilanciaBR/fludashboard/fludashboard/app.py", line 42, in startup
    debug=settings.APP_DEBUG
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/flask/app.py", line 841, in run
    run_simple(host, port, self, **options)
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/werkzeug/serving.py", line 720, in run_simple
    s.bind((hostname, port))
OSError: [Errno 98] Address already in use
2017-10-24 19:23:31 [23806] [INFO] Worker exiting (pid: 23806)
2017-10-24 19:23:31 [23803] [INFO] Worker exiting (pid: 23803)
2017-10-24 19:23:31 [23800] [INFO] Shutting down: Master
2017-10-24 19:23:31 [23800] [INFO] Reason: Worker failed to boot.
2017-10-24 19:23:38 [23897] [INFO] Starting gunicorn 19.1.0
2017-10-24 19:23:38 [23897] [INFO] Listening at: http://0.0.0.0:8000 (23897)
2017-10-24 19:23:38 [23897] [INFO] Using worker: sync
2017-10-24 19:23:38 [23900] [INFO] Booting worker with pid: 23900
2017-10-24 19:23:38 [23901] [INFO] Booting worker with pid: 23901
2017-10-24 19:23:38 [23902] [INFO] Booting worker with pid: 23902
2017-10-24 19:23:38 [23903] [INFO] Booting worker with pid: 23903
2017-10-24 19:23:38 [23897] [INFO] 4 workers
2017-10-24 19:23:39 [23901] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/gunicorn-19.1.0-py3.6.egg/gunicorn/arbiter.py", line 507, in spawn_worker
    worker.init_process()
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/gunicorn-19.1.0-py3.6.egg/gunicorn/workers/base.py", line 114, in init_process
    self.wsgi = self.app.wsgi()
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/gunicorn-19.1.0-py3.6.egg/gunicorn/app/base.py", line 66, in wsgi
    self.callable = self.load()
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/gunicorn-19.1.0-py3.6.egg/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/gunicorn-19.1.0-py3.6.egg/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/gunicorn-19.1.0-py3.6.egg/gunicorn/util.py", line 367, in import_app
    app = eval(obj, mod.__dict__)
  File "<string>", line 1, in <module>
  File "/home/xmn/dev/FluVigilanciaBR/fludashboard/fludashboard/app.py", line 42, in startup
    debug=settings.APP_DEBUG
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/flask/app.py", line 841, in run
    run_simple(host, port, self, **options)
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/werkzeug/serving.py", line 720, in run_simple
    s.bind((hostname, port))
OSError: [Errno 98] Address already in use
Traceback (most recent call last):
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/gunicorn-19.1.0-py3.6.egg/gunicorn/arbiter.py", line 507, in spawn_worker
    worker.init_process()
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/gunicorn-19.1.0-py3.6.egg/gunicorn/workers/base.py", line 114, in init_process
    self.wsgi = self.app.wsgi()
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/gunicorn-19.1.0-py3.6.egg/gunicorn/app/base.py", line 66, in wsgi
    self.callable = self.load()
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/gunicorn-19.1.0-py3.6.egg/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/gunicorn-19.1.0-py3.6.egg/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/gunicorn-19.1.0-py3.6.egg/gunicorn/util.py", line 367, in import_app
    app = eval(obj, mod.__dict__)
  File "<string>", line 1, in <module>
  File "/home/xmn/dev/FluVigilanciaBR/fludashboard/fludashboard/app.py", line 42, in startup
    debug=settings.APP_DEBUG
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/flask/app.py", line 841, in run
    run_simple(host, port, self, **options)
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/werkzeug/serving.py", line 720, in run_simple
    s.bind((hostname, port))
OSError: [Errno 98] Address already in use
2017-10-24 19:23:39 [23901] [INFO] Worker exiting (pid: 23901)
2017-10-24 19:23:39 [23902] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/gunicorn-19.1.0-py3.6.egg/gunicorn/arbiter.py", line 507, in spawn_worker
    worker.init_process()
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/gunicorn-19.1.0-py3.6.egg/gunicorn/workers/base.py", line 114, in init_process
    self.wsgi = self.app.wsgi()
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/gunicorn-19.1.0-py3.6.egg/gunicorn/app/base.py", line 66, in wsgi
    self.callable = self.load()
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/gunicorn-19.1.0-py3.6.egg/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/gunicorn-19.1.0-py3.6.egg/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/gunicorn-19.1.0-py3.6.egg/gunicorn/util.py", line 367, in import_app
    app = eval(obj, mod.__dict__)
  File "<string>", line 1, in <module>
  File "/home/xmn/dev/FluVigilanciaBR/fludashboard/fludashboard/app.py", line 42, in startup
    debug=settings.APP_DEBUG
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/flask/app.py", line 841, in run
    run_simple(host, port, self, **options)
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/werkzeug/serving.py", line 720, in run_simple
    s.bind((hostname, port))
OSError: [Errno 98] Address already in use
Traceback (most recent call last):
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/gunicorn-19.1.0-py3.6.egg/gunicorn/arbiter.py", line 507, in spawn_worker
    worker.init_process()
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/gunicorn-19.1.0-py3.6.egg/gunicorn/workers/base.py", line 114, in init_process
    self.wsgi = self.app.wsgi()
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/gunicorn-19.1.0-py3.6.egg/gunicorn/app/base.py", line 66, in wsgi
    self.callable = self.load()
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/gunicorn-19.1.0-py3.6.egg/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/gunicorn-19.1.0-py3.6.egg/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/gunicorn-19.1.0-py3.6.egg/gunicorn/util.py", line 367, in import_app
    app = eval(obj, mod.__dict__)
  File "<string>", line 1, in <module>
  File "/home/xmn/dev/FluVigilanciaBR/fludashboard/fludashboard/app.py", line 42, in startup
    debug=settings.APP_DEBUG
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/flask/app.py", line 841, in run
    run_simple(host, port, self, **options)
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/werkzeug/serving.py", line 720, in run_simple
    s.bind((hostname, port))
OSError: [Errno 98] Address already in use
2017-10-24 19:23:39 [23902] [INFO] Worker exiting (pid: 23902)
2017-10-24 19:23:39 [23903] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/gunicorn-19.1.0-py3.6.egg/gunicorn/arbiter.py", line 507, in spawn_worker
    worker.init_process()
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/gunicorn-19.1.0-py3.6.egg/gunicorn/workers/base.py", line 114, in init_process
    self.wsgi = self.app.wsgi()
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/gunicorn-19.1.0-py3.6.egg/gunicorn/app/base.py", line 66, in wsgi
    self.callable = self.load()
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/gunicorn-19.1.0-py3.6.egg/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/gunicorn-19.1.0-py3.6.egg/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/gunicorn-19.1.0-py3.6.egg/gunicorn/util.py", line 367, in import_app
    app = eval(obj, mod.__dict__)
  File "<string>", line 1, in <module>
  File "/home/xmn/dev/FluVigilanciaBR/fludashboard/fludashboard/app.py", line 42, in startup
    debug=settings.APP_DEBUG
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/flask/app.py", line 841, in run
    run_simple(host, port, self, **options)
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/werkzeug/serving.py", line 720, in run_simple
    s.bind((hostname, port))
OSError: [Errno 98] Address already in use
Traceback (most recent call last):
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/gunicorn-19.1.0-py3.6.egg/gunicorn/arbiter.py", line 507, in spawn_worker
    worker.init_process()
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/gunicorn-19.1.0-py3.6.egg/gunicorn/workers/base.py", line 114, in init_process
    self.wsgi = self.app.wsgi()
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/gunicorn-19.1.0-py3.6.egg/gunicorn/app/base.py", line 66, in wsgi
    self.callable = self.load()
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/gunicorn-19.1.0-py3.6.egg/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/gunicorn-19.1.0-py3.6.egg/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/gunicorn-19.1.0-py3.6.egg/gunicorn/util.py", line 367, in import_app
    app = eval(obj, mod.__dict__)
  File "<string>", line 1, in <module>
  File "/home/xmn/dev/FluVigilanciaBR/fludashboard/fludashboard/app.py", line 42, in startup
    debug=settings.APP_DEBUG
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/flask/app.py", line 841, in run
    run_simple(host, port, self, **options)
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/werkzeug/serving.py", line 720, in run_simple
    s.bind((hostname, port))
OSError: [Errno 98] Address already in use
2017-10-24 19:23:39 [23903] [INFO] Worker exiting (pid: 23903)
2017-10-24 19:23:40 [23900] [INFO] Worker exiting (pid: 23900)
2017-10-24 19:23:40 [23897] [INFO] Shutting down: Master
2017-10-24 19:23:40 [23897] [INFO] Reason: Worker failed to boot.
2017-10-24 19:24:03 [24000] [INFO] Starting gunicorn 19.1.0
2017-10-24 19:24:03 [24000] [INFO] Listening at: http://0.0.0.0:8000 (24000)
2017-10-24 19:24:03 [24000] [INFO] Using worker: sync
2017-10-24 19:24:03 [24003] [INFO] Booting worker with pid: 24003
2017-10-24 19:24:03 [24004] [INFO] Booting worker with pid: 24004
2017-10-24 19:24:03 [24005] [INFO] Booting worker with pid: 24005
2017-10-24 19:24:03 [24006] [INFO] Booting worker with pid: 24006
2017-10-24 19:24:03 [24000] [INFO] 4 workers
2017-10-24 19:24:05 [24003] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/gunicorn-19.1.0-py3.6.egg/gunicorn/arbiter.py", line 507, in spawn_worker
    worker.init_process()
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/gunicorn-19.1.0-py3.6.egg/gunicorn/workers/base.py", line 114, in init_process
    self.wsgi = self.app.wsgi()
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/gunicorn-19.1.0-py3.6.egg/gunicorn/app/base.py", line 66, in wsgi
    self.callable = self.load()
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/gunicorn-19.1.0-py3.6.egg/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/gunicorn-19.1.0-py3.6.egg/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/gunicorn-19.1.0-py3.6.egg/gunicorn/util.py", line 367, in import_app
    app = eval(obj, mod.__dict__)
  File "<string>", line 1, in <module>
  File "/home/xmn/dev/FluVigilanciaBR/fludashboard/fludashboard/app.py", line 42, in startup
    debug=settings.APP_DEBUG
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/flask/app.py", line 841, in run
    run_simple(host, port, self, **options)
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/werkzeug/serving.py", line 720, in run_simple
    s.bind((hostname, port))
OSError: [Errno 98] Address already in use
Traceback (most recent call last):
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/gunicorn-19.1.0-py3.6.egg/gunicorn/arbiter.py", line 507, in spawn_worker
    worker.init_process()
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/gunicorn-19.1.0-py3.6.egg/gunicorn/workers/base.py", line 114, in init_process
    self.wsgi = self.app.wsgi()
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/gunicorn-19.1.0-py3.6.egg/gunicorn/app/base.py", line 66, in wsgi
    self.callable = self.load()
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/gunicorn-19.1.0-py3.6.egg/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/gunicorn-19.1.0-py3.6.egg/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/gunicorn-19.1.0-py3.6.egg/gunicorn/util.py", line 367, in import_app
    app = eval(obj, mod.__dict__)
  File "<string>", line 1, in <module>
  File "/home/xmn/dev/FluVigilanciaBR/fludashboard/fludashboard/app.py", line 42, in startup
    debug=settings.APP_DEBUG
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/flask/app.py", line 841, in run
    run_simple(host, port, self, **options)
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/werkzeug/serving.py", line 720, in run_simple
    s.bind((hostname, port))
OSError: [Errno 98] Address already in use
2017-10-24 19:24:05 [24003] [INFO] Worker exiting (pid: 24003)
2017-10-24 19:24:05 [24005] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/gunicorn-19.1.0-py3.6.egg/gunicorn/arbiter.py", line 507, in spawn_worker
    worker.init_process()
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/gunicorn-19.1.0-py3.6.egg/gunicorn/workers/base.py", line 114, in init_process
    self.wsgi = self.app.wsgi()
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/gunicorn-19.1.0-py3.6.egg/gunicorn/app/base.py", line 66, in wsgi
    self.callable = self.load()
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/gunicorn-19.1.0-py3.6.egg/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/gunicorn-19.1.0-py3.6.egg/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/gunicorn-19.1.0-py3.6.egg/gunicorn/util.py", line 367, in import_app
    app = eval(obj, mod.__dict__)
  File "<string>", line 1, in <module>
  File "/home/xmn/dev/FluVigilanciaBR/fludashboard/fludashboard/app.py", line 42, in startup
    debug=settings.APP_DEBUG
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/flask/app.py", line 841, in run
    run_simple(host, port, self, **options)
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/werkzeug/serving.py", line 720, in run_simple
    s.bind((hostname, port))
OSError: [Errno 98] Address already in use
Traceback (most recent call last):
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/gunicorn-19.1.0-py3.6.egg/gunicorn/arbiter.py", line 507, in spawn_worker
    worker.init_process()
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/gunicorn-19.1.0-py3.6.egg/gunicorn/workers/base.py", line 114, in init_process
    self.wsgi = self.app.wsgi()
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/gunicorn-19.1.0-py3.6.egg/gunicorn/app/base.py", line 66, in wsgi
    self.callable = self.load()
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/gunicorn-19.1.0-py3.6.egg/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/gunicorn-19.1.0-py3.6.egg/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/gunicorn-19.1.0-py3.6.egg/gunicorn/util.py", line 367, in import_app
    app = eval(obj, mod.__dict__)
  File "<string>", line 1, in <module>
  File "/home/xmn/dev/FluVigilanciaBR/fludashboard/fludashboard/app.py", line 42, in startup
    debug=settings.APP_DEBUG
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/flask/app.py", line 841, in run
    run_simple(host, port, self, **options)
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/werkzeug/serving.py", line 720, in run_simple
    s.bind((hostname, port))
OSError: [Errno 98] Address already in use
2017-10-24 19:24:05 [24005] [INFO] Worker exiting (pid: 24005)
2017-10-24 19:24:05 [24006] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/gunicorn-19.1.0-py3.6.egg/gunicorn/arbiter.py", line 507, in spawn_worker
    worker.init_process()
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/gunicorn-19.1.0-py3.6.egg/gunicorn/workers/base.py", line 114, in init_process
    self.wsgi = self.app.wsgi()
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/gunicorn-19.1.0-py3.6.egg/gunicorn/app/base.py", line 66, in wsgi
    self.callable = self.load()
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/gunicorn-19.1.0-py3.6.egg/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/gunicorn-19.1.0-py3.6.egg/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/gunicorn-19.1.0-py3.6.egg/gunicorn/util.py", line 367, in import_app
    app = eval(obj, mod.__dict__)
  File "<string>", line 1, in <module>
  File "/home/xmn/dev/FluVigilanciaBR/fludashboard/fludashboard/app.py", line 42, in startup
    debug=settings.APP_DEBUG
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/flask/app.py", line 841, in run
    run_simple(host, port, self, **options)
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/werkzeug/serving.py", line 720, in run_simple
    s.bind((hostname, port))
OSError: [Errno 98] Address already in use
Traceback (most recent call last):
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/gunicorn-19.1.0-py3.6.egg/gunicorn/arbiter.py", line 507, in spawn_worker
    worker.init_process()
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/gunicorn-19.1.0-py3.6.egg/gunicorn/workers/base.py", line 114, in init_process
    self.wsgi = self.app.wsgi()
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/gunicorn-19.1.0-py3.6.egg/gunicorn/app/base.py", line 66, in wsgi
    self.callable = self.load()
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/gunicorn-19.1.0-py3.6.egg/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/gunicorn-19.1.0-py3.6.egg/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/gunicorn-19.1.0-py3.6.egg/gunicorn/util.py", line 367, in import_app
    app = eval(obj, mod.__dict__)
  File "<string>", line 1, in <module>
  File "/home/xmn/dev/FluVigilanciaBR/fludashboard/fludashboard/app.py", line 42, in startup
    debug=settings.APP_DEBUG
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/flask/app.py", line 841, in run
    run_simple(host, port, self, **options)
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/werkzeug/serving.py", line 720, in run_simple
    s.bind((hostname, port))
OSError: [Errno 98] Address already in use
2017-10-24 19:24:05 [24006] [INFO] Worker exiting (pid: 24006)
2017-10-24 19:24:05 [24004] [INFO] Worker exiting (pid: 24004)
2017-10-24 19:24:05 [24000] [INFO] Shutting down: Master
2017-10-24 19:24:05 [24000] [INFO] Reason: Worker failed to boot.
2017-10-24 19:24:35 [24109] [INFO] Starting gunicorn 19.1.0
2017-10-24 19:24:35 [24109] [INFO] Listening at: http://0.0.0.0:8000 (24109)
2017-10-24 19:24:35 [24109] [INFO] Using worker: sync
2017-10-24 19:24:35 [24113] [INFO] Booting worker with pid: 24113
2017-10-24 19:24:35 [24114] [INFO] Booting worker with pid: 24114
2017-10-24 19:24:35 [24115] [INFO] Booting worker with pid: 24115
2017-10-24 19:24:35 [24116] [INFO] Booting worker with pid: 24116
2017-10-24 19:24:35 [24109] [INFO] 4 workers
2017-10-24 19:24:36 [24114] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/gunicorn-19.1.0-py3.6.egg/gunicorn/arbiter.py", line 507, in spawn_worker
    worker.init_process()
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/gunicorn-19.1.0-py3.6.egg/gunicorn/workers/base.py", line 114, in init_process
    self.wsgi = self.app.wsgi()
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/gunicorn-19.1.0-py3.6.egg/gunicorn/app/base.py", line 66, in wsgi
    self.callable = self.load()
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/gunicorn-19.1.0-py3.6.egg/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/gunicorn-19.1.0-py3.6.egg/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/gunicorn-19.1.0-py3.6.egg/gunicorn/util.py", line 367, in import_app
    app = eval(obj, mod.__dict__)
  File "<string>", line 1, in <module>
  File "/home/xmn/dev/FluVigilanciaBR/fludashboard/fludashboard/app.py", line 42, in startup
    debug=settings.APP_DEBUG
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/flask/app.py", line 841, in run
    run_simple(host, port, self, **options)
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/werkzeug/serving.py", line 720, in run_simple
    s.bind((hostname, port))
OSError: [Errno 98] Address already in use
Traceback (most recent call last):
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/gunicorn-19.1.0-py3.6.egg/gunicorn/arbiter.py", line 507, in spawn_worker
    worker.init_process()
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/gunicorn-19.1.0-py3.6.egg/gunicorn/workers/base.py", line 114, in init_process
    self.wsgi = self.app.wsgi()
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/gunicorn-19.1.0-py3.6.egg/gunicorn/app/base.py", line 66, in wsgi
    self.callable = self.load()
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/gunicorn-19.1.0-py3.6.egg/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/gunicorn-19.1.0-py3.6.egg/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/gunicorn-19.1.0-py3.6.egg/gunicorn/util.py", line 367, in import_app
    app = eval(obj, mod.__dict__)
  File "<string>", line 1, in <module>
  File "/home/xmn/dev/FluVigilanciaBR/fludashboard/fludashboard/app.py", line 42, in startup
    debug=settings.APP_DEBUG
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/flask/app.py", line 841, in run
    run_simple(host, port, self, **options)
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/werkzeug/serving.py", line 720, in run_simple
    s.bind((hostname, port))
OSError: [Errno 98] Address already in use
2017-10-24 19:24:36 [24114] [INFO] Worker exiting (pid: 24114)
2017-10-24 19:24:36 [24115] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/gunicorn-19.1.0-py3.6.egg/gunicorn/arbiter.py", line 507, in spawn_worker
    worker.init_process()
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/gunicorn-19.1.0-py3.6.egg/gunicorn/workers/base.py", line 114, in init_process
    self.wsgi = self.app.wsgi()
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/gunicorn-19.1.0-py3.6.egg/gunicorn/app/base.py", line 66, in wsgi
    self.callable = self.load()
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/gunicorn-19.1.0-py3.6.egg/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/gunicorn-19.1.0-py3.6.egg/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/gunicorn-19.1.0-py3.6.egg/gunicorn/util.py", line 367, in import_app
    app = eval(obj, mod.__dict__)
  File "<string>", line 1, in <module>
  File "/home/xmn/dev/FluVigilanciaBR/fludashboard/fludashboard/app.py", line 42, in startup
    debug=settings.APP_DEBUG
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/flask/app.py", line 841, in run
    run_simple(host, port, self, **options)
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/werkzeug/serving.py", line 720, in run_simple
    s.bind((hostname, port))
OSError: [Errno 98] Address already in use
Traceback (most recent call last):
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/gunicorn-19.1.0-py3.6.egg/gunicorn/arbiter.py", line 507, in spawn_worker
    worker.init_process()
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/gunicorn-19.1.0-py3.6.egg/gunicorn/workers/base.py", line 114, in init_process
    self.wsgi = self.app.wsgi()
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/gunicorn-19.1.0-py3.6.egg/gunicorn/app/base.py", line 66, in wsgi
    self.callable = self.load()
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/gunicorn-19.1.0-py3.6.egg/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/gunicorn-19.1.0-py3.6.egg/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/gunicorn-19.1.0-py3.6.egg/gunicorn/util.py", line 367, in import_app
    app = eval(obj, mod.__dict__)
  File "<string>", line 1, in <module>
  File "/home/xmn/dev/FluVigilanciaBR/fludashboard/fludashboard/app.py", line 42, in startup
    debug=settings.APP_DEBUG
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/flask/app.py", line 841, in run
    run_simple(host, port, self, **options)
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/werkzeug/serving.py", line 720, in run_simple
    s.bind((hostname, port))
OSError: [Errno 98] Address already in use
2017-10-24 19:24:36 [24115] [INFO] Worker exiting (pid: 24115)
2017-10-24 19:24:36 [24116] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/gunicorn-19.1.0-py3.6.egg/gunicorn/arbiter.py", line 507, in spawn_worker
    worker.init_process()
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/gunicorn-19.1.0-py3.6.egg/gunicorn/workers/base.py", line 114, in init_process
    self.wsgi = self.app.wsgi()
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/gunicorn-19.1.0-py3.6.egg/gunicorn/app/base.py", line 66, in wsgi
    self.callable = self.load()
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/gunicorn-19.1.0-py3.6.egg/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/gunicorn-19.1.0-py3.6.egg/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/gunicorn-19.1.0-py3.6.egg/gunicorn/util.py", line 367, in import_app
    app = eval(obj, mod.__dict__)
  File "<string>", line 1, in <module>
  File "/home/xmn/dev/FluVigilanciaBR/fludashboard/fludashboard/app.py", line 42, in startup
    debug=settings.APP_DEBUG
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/flask/app.py", line 841, in run
    run_simple(host, port, self, **options)
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/werkzeug/serving.py", line 720, in run_simple
    s.bind((hostname, port))
OSError: [Errno 98] Address already in use
Traceback (most recent call last):
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/gunicorn-19.1.0-py3.6.egg/gunicorn/arbiter.py", line 507, in spawn_worker
    worker.init_process()
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/gunicorn-19.1.0-py3.6.egg/gunicorn/workers/base.py", line 114, in init_process
    self.wsgi = self.app.wsgi()
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/gunicorn-19.1.0-py3.6.egg/gunicorn/app/base.py", line 66, in wsgi
    self.callable = self.load()
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/gunicorn-19.1.0-py3.6.egg/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/gunicorn-19.1.0-py3.6.egg/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/gunicorn-19.1.0-py3.6.egg/gunicorn/util.py", line 367, in import_app
    app = eval(obj, mod.__dict__)
  File "<string>", line 1, in <module>
  File "/home/xmn/dev/FluVigilanciaBR/fludashboard/fludashboard/app.py", line 42, in startup
    debug=settings.APP_DEBUG
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/flask/app.py", line 841, in run
    run_simple(host, port, self, **options)
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/werkzeug/serving.py", line 720, in run_simple
    s.bind((hostname, port))
OSError: [Errno 98] Address already in use
2017-10-24 19:24:36 [24116] [INFO] Worker exiting (pid: 24116)
2017-10-24 19:24:36 [24113] [INFO] Worker exiting (pid: 24113)
2017-10-24 19:24:37 [24109] [INFO] Shutting down: Master
2017-10-24 19:24:37 [24109] [INFO] Reason: Worker failed to boot.
2017-10-24 19:24:52 [24219] [INFO] Starting gunicorn 19.1.0
2017-10-24 19:24:52 [24219] [INFO] Listening at: http://0.0.0.0:8000 (24219)
2017-10-24 19:24:52 [24219] [INFO] Using worker: sync
2017-10-24 19:24:52 [24222] [INFO] Booting worker with pid: 24222
2017-10-24 19:24:52 [24224] [INFO] Booting worker with pid: 24224
2017-10-24 19:24:52 [24225] [INFO] Booting worker with pid: 24225
2017-10-24 19:24:52 [24226] [INFO] Booting worker with pid: 24226
2017-10-24 19:24:53 [24219] [INFO] 4 workers
2017-10-24 19:24:54 [24224] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/gunicorn-19.1.0-py3.6.egg/gunicorn/arbiter.py", line 507, in spawn_worker
    worker.init_process()
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/gunicorn-19.1.0-py3.6.egg/gunicorn/workers/base.py", line 114, in init_process
    self.wsgi = self.app.wsgi()
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/gunicorn-19.1.0-py3.6.egg/gunicorn/app/base.py", line 66, in wsgi
    self.callable = self.load()
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/gunicorn-19.1.0-py3.6.egg/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/gunicorn-19.1.0-py3.6.egg/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/gunicorn-19.1.0-py3.6.egg/gunicorn/util.py", line 367, in import_app
    app = eval(obj, mod.__dict__)
  File "<string>", line 1, in <module>
  File "/home/xmn/dev/FluVigilanciaBR/fludashboard/fludashboard/app.py", line 42, in startup
    debug=settings.APP_DEBUG
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/flask/app.py", line 841, in run
    run_simple(host, port, self, **options)
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/werkzeug/serving.py", line 720, in run_simple
    s.bind((hostname, port))
OSError: [Errno 98] Address already in use
Traceback (most recent call last):
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/gunicorn-19.1.0-py3.6.egg/gunicorn/arbiter.py", line 507, in spawn_worker
    worker.init_process()
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/gunicorn-19.1.0-py3.6.egg/gunicorn/workers/base.py", line 114, in init_process
    self.wsgi = self.app.wsgi()
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/gunicorn-19.1.0-py3.6.egg/gunicorn/app/base.py", line 66, in wsgi
    self.callable = self.load()
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/gunicorn-19.1.0-py3.6.egg/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/gunicorn-19.1.0-py3.6.egg/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/gunicorn-19.1.0-py3.6.egg/gunicorn/util.py", line 367, in import_app
    app = eval(obj, mod.__dict__)
  File "<string>", line 1, in <module>
  File "/home/xmn/dev/FluVigilanciaBR/fludashboard/fludashboard/app.py", line 42, in startup
    debug=settings.APP_DEBUG
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/flask/app.py", line 841, in run
    run_simple(host, port, self, **options)
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/werkzeug/serving.py", line 720, in run_simple
    s.bind((hostname, port))
OSError: [Errno 98] Address already in use
2017-10-24 19:24:54 [24224] [INFO] Worker exiting (pid: 24224)
2017-10-24 19:24:54 [24225] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/gunicorn-19.1.0-py3.6.egg/gunicorn/arbiter.py", line 507, in spawn_worker
    worker.init_process()
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/gunicorn-19.1.0-py3.6.egg/gunicorn/workers/base.py", line 114, in init_process
    self.wsgi = self.app.wsgi()
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/gunicorn-19.1.0-py3.6.egg/gunicorn/app/base.py", line 66, in wsgi
    self.callable = self.load()
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/gunicorn-19.1.0-py3.6.egg/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/gunicorn-19.1.0-py3.6.egg/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/gunicorn-19.1.0-py3.6.egg/gunicorn/util.py", line 367, in import_app
    app = eval(obj, mod.__dict__)
  File "<string>", line 1, in <module>
  File "/home/xmn/dev/FluVigilanciaBR/fludashboard/fludashboard/app.py", line 42, in startup
    debug=settings.APP_DEBUG
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/flask/app.py", line 841, in run
    run_simple(host, port, self, **options)
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/werkzeug/serving.py", line 720, in run_simple
    s.bind((hostname, port))
OSError: [Errno 98] Address already in use
Traceback (most recent call last):
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/gunicorn-19.1.0-py3.6.egg/gunicorn/arbiter.py", line 507, in spawn_worker
    worker.init_process()
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/gunicorn-19.1.0-py3.6.egg/gunicorn/workers/base.py", line 114, in init_process
    self.wsgi = self.app.wsgi()
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/gunicorn-19.1.0-py3.6.egg/gunicorn/app/base.py", line 66, in wsgi
    self.callable = self.load()
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/gunicorn-19.1.0-py3.6.egg/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/gunicorn-19.1.0-py3.6.egg/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/gunicorn-19.1.0-py3.6.egg/gunicorn/util.py", line 367, in import_app
    app = eval(obj, mod.__dict__)
  File "<string>", line 1, in <module>
  File "/home/xmn/dev/FluVigilanciaBR/fludashboard/fludashboard/app.py", line 42, in startup
    debug=settings.APP_DEBUG
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/flask/app.py", line 841, in run
    run_simple(host, port, self, **options)
  File "/home/xmn/miniconda3/envs/fludashboard/lib/python3.6/site-packages/werkzeug/serving.py", line 720, in run_simple
    s.bind((hostname, port))
OSError: [Errno 98] Address already in use
2017-10-24 19:24:54 [24225] [INFO] Worker exiting (pid: 24225)
2017-10-24 19:24:54 [24222] [INFO] Worker exiting (pid: 24222)
2017-10-24 19:24:54 [24226] [INFO] Worker exiting (pid: 24226)
2017-10-24 19:24:55 [24219] [INFO] Shutting down: Master
2017-10-24 19:24:55 [24219] [INFO] Reason: Worker failed to boot.
2017-10-24 19:27:33 [24389] [INFO] Starting gunicorn 19.1.0
2017-10-24 19:27:33 [24389] [INFO] Listening at: http://0.0.0.0:8000 (24389)
2017-10-24 19:27:33 [24389] [INFO] Using worker: sync
2017-10-24 19:27:33 [24392] [INFO] Booting worker with pid: 24392
2017-10-24 19:27:33 [24393] [INFO] Booting worker with pid: 24393
2017-10-24 19:27:33 [24394] [INFO] Booting worker with pid: 24394
2017-10-24 19:27:33 [24395] [INFO] Booting worker with pid: 24395
2017-10-24 19:27:33 [24389] [INFO] 4 workers
2017-10-24 19:27:38 [24393] [INFO] Worker exiting (pid: 24393)
2017-10-24 19:27:38 [24394] [INFO] Worker exiting (pid: 24394)
2017-10-24 19:27:38 [24392] [INFO] Worker exiting (pid: 24392)
2017-10-24 19:27:38 [24395] [INFO] Worker exiting (pid: 24395)
2017-10-24 19:27:38 [24389] [INFO] 4 workers
2017-10-24 19:27:38 [24389] [INFO] Handling signal: int
2017-10-24 19:27:38 [24389] [INFO] Shutting down: Master
2017-10-24 19:27:59 [24470] [INFO] Starting gunicorn 19.1.0
2017-10-24 19:27:59 [24470] [INFO] Listening at: http://0.0.0.0:8000 (24470)
2017-10-24 19:27:59 [24470] [INFO] Using worker: sync
2017-10-24 19:27:59 [24473] [INFO] Booting worker with pid: 24473
2017-10-24 19:27:59 [24474] [INFO] Booting worker with pid: 24474
2017-10-24 19:27:59 [24475] [INFO] Booting worker with pid: 24475
2017-10-24 19:27:59 [24476] [INFO] Booting worker with pid: 24476
2017-10-24 19:27:59 [24470] [INFO] 4 workers
2017-10-24 19:28:29 [24470] [INFO] 4 workers
2017-10-24 19:28:31 [24475] [INFO] Worker exiting (pid: 24475)
2017-10-24 19:28:31 [24474] [INFO] Worker exiting (pid: 24474)
2017-10-24 19:28:31 [24476] [INFO] Worker exiting (pid: 24476)
2017-10-24 19:28:31 [24473] [INFO] Worker exiting (pid: 24473)
2017-10-24 19:28:31 [24470] [INFO] 4 workers
2017-10-24 19:28:31 [24470] [INFO] Handling signal: int
2017-10-24 19:28:32 [24470] [INFO] Shutting down: Master
2017-10-24 19:31:21 [24623] [INFO] Starting gunicorn 19.1.0
2017-10-24 19:31:21 [24623] [INFO] Listening at: http://0.0.0.0:8000 (24623)
2017-10-24 19:31:21 [24623] [INFO] Using worker: sync
2017-10-24 19:31:21 [24626] [INFO] Booting worker with pid: 24626
2017-10-24 19:31:21 [24627] [INFO] Booting worker with pid: 24627
2017-10-24 19:31:21 [24628] [INFO] Booting worker with pid: 24628
2017-10-24 19:31:21 [24629] [INFO] Booting worker with pid: 24629
2017-10-24 19:31:21 [24623] [INFO] 4 workers
2017-10-24 19:31:51 [24623] [INFO] 4 workers
2017-10-24 19:32:08 [24623] [INFO] 4 workers
2017-10-24 19:32:23 [24623] [INFO] 4 workers
2017-10-24 19:32:38 [24623] [INFO] 4 workers
2017-10-24 19:32:53 [24623] [INFO] 4 workers
2017-10-24 19:33:08 [24623] [INFO] 4 workers
2017-10-24 19:33:23 [24623] [INFO] 4 workers
2017-10-24 19:33:39 [24629] [INFO] Worker exiting (pid: 24629)
2017-10-24 19:33:39 [24628] [INFO] Worker exiting (pid: 24628)
2017-10-24 19:33:39 [24626] [INFO] Worker exiting (pid: 24626)
2017-10-24 19:33:39 [24627] [INFO] Worker exiting (pid: 24627)
2017-10-24 19:33:39 [24623] [INFO] 4 workers
2017-10-24 19:33:39 [24623] [INFO] Handling signal: int
2017-10-24 19:33:40 [24623] [INFO] Shutting down: Master
2017-10-24 20:00:49 [25557] [INFO] Starting gunicorn 19.1.0
2017-10-24 20:00:49 [25557] [INFO] Listening at: http://0.0.0.0:8000 (25557)
2017-10-24 20:00:49 [25557] [INFO] Using worker: sync
2017-10-24 20:00:49 [25560] [INFO] Booting worker with pid: 25560
2017-10-24 20:00:49 [25561] [INFO] Booting worker with pid: 25561
2017-10-24 20:00:49 [25562] [INFO] Booting worker with pid: 25562
2017-10-24 20:00:49 [25563] [INFO] Booting worker with pid: 25563
2017-10-24 20:00:49 [25557] [INFO] 4 workers
2017-10-24 20:01:19 [25557] [INFO] 4 workers
2017-10-24 20:01:35 [25557] [INFO] 4 workers
2017-10-24 20:01:50 [25557] [INFO] 4 workers
2017-10-24 20:02:05 [25557] [INFO] 4 workers
2017-10-24 20:02:20 [25557] [INFO] 4 workers
2017-10-24 20:02:35 [25557] [INFO] 4 workers
2017-10-24 20:02:50 [25557] [INFO] 4 workers
2017-10-24 20:03:05 [25557] [INFO] 4 workers
2017-10-24 20:03:20 [25557] [INFO] 4 workers
2017-10-24 20:03:35 [25557] [INFO] 4 workers
2017-10-24 20:03:50 [25557] [INFO] 4 workers
2017-10-24 20:04:05 [25557] [INFO] 4 workers
2017-10-24 20:04:20 [25557] [INFO] 4 workers
2017-10-24 20:04:35 [25557] [INFO] 4 workers
2017-10-24 20:04:51 [25557] [INFO] 4 workers
2017-10-24 20:05:06 [25557] [INFO] 4 workers
2017-10-24 20:05:21 [25557] [INFO] 4 workers
2017-10-24 20:05:36 [25557] [INFO] 4 workers
2017-10-24 20:05:51 [25557] [INFO] 4 workers
2017-10-24 20:06:06 [25557] [INFO] 4 workers
2017-10-24 20:06:21 [25557] [INFO] 4 workers
2017-10-24 20:06:36 [25557] [INFO] 4 workers
2017-10-24 20:06:51 [25557] [INFO] 4 workers
2017-10-24 20:07:06 [25557] [INFO] 4 workers
2017-10-24 20:07:21 [25557] [INFO] 4 workers
2017-10-24 20:07:36 [25557] [INFO] 4 workers
2017-10-24 20:07:51 [25557] [INFO] 4 workers
2017-10-24 20:08:06 [25557] [INFO] 4 workers
2017-10-24 20:08:21 [25557] [INFO] 4 workers
2017-10-24 20:08:36 [25557] [INFO] 4 workers
2017-10-24 20:08:51 [25557] [INFO] 4 workers
2017-10-24 20:09:06 [25557] [INFO] 4 workers
2017-10-24 20:09:21 [25557] [INFO] 4 workers
2017-10-24 20:09:36 [25557] [INFO] 4 workers
2017-10-24 20:09:51 [25557] [INFO] 4 workers
2017-10-24 20:10:06 [25557] [INFO] 4 workers
2017-10-24 20:10:21 [25557] [INFO] 4 workers
2017-10-24 20:10:36 [25557] [INFO] 4 workers
2017-10-24 20:10:51 [25557] [INFO] 4 workers
2017-10-24 20:11:06 [25557] [INFO] 4 workers
2017-10-24 20:11:21 [25557] [INFO] 4 workers
2017-10-24 20:11:36 [25557] [INFO] 4 workers
2017-10-24 20:11:51 [25557] [INFO] 4 workers
2017-10-24 20:12:06 [25557] [INFO] 4 workers
2017-10-24 20:12:21 [25557] [INFO] 4 workers
2017-10-24 20:12:36 [25557] [INFO] 4 workers
2017-10-24 20:12:51 [25557] [INFO] 4 workers
2017-10-24 20:13:06 [25557] [INFO] 4 workers
2017-10-24 20:13:21 [25557] [INFO] 4 workers
2017-10-24 20:13:36 [25557] [INFO] 4 workers
2017-10-24 20:13:51 [25557] [INFO] 4 workers
2017-10-24 20:14:06 [25557] [INFO] 4 workers
2017-10-24 20:14:21 [25557] [INFO] 4 workers
2017-10-24 20:14:36 [25557] [INFO] 4 workers
2017-10-24 20:14:51 [25557] [INFO] 4 workers
2017-10-24 20:15:06 [25557] [INFO] 4 workers
2017-10-24 20:15:21 [25557] [INFO] 4 workers
2017-10-24 20:15:36 [25557] [INFO] 4 workers
2017-10-24 20:15:51 [25557] [INFO] 4 workers
2017-10-24 20:16:06 [25557] [INFO] 4 workers
2017-10-24 20:16:21 [25557] [INFO] 4 workers
2017-10-24 20:16:36 [25557] [INFO] 4 workers
2017-10-24 20:16:51 [25557] [INFO] 4 workers
2017-10-24 20:17:06 [25557] [INFO] 4 workers
2017-10-24 20:17:21 [25557] [INFO] 4 workers
2017-10-24 20:17:36 [25557] [INFO] 4 workers
2017-10-24 20:17:51 [25557] [INFO] 4 workers
2017-10-24 20:18:06 [25557] [INFO] 4 workers
2017-10-24 20:18:21 [25557] [INFO] 4 workers
2017-10-24 20:18:36 [25557] [INFO] 4 workers
2017-10-24 20:18:51 [25557] [INFO] 4 workers
2017-10-24 20:19:06 [25557] [INFO] 4 workers
2017-10-24 20:19:21 [25557] [INFO] 4 workers
2017-10-24 20:19:36 [25557] [INFO] 4 workers
2017-10-24 20:19:51 [25557] [INFO] 4 workers
2017-10-24 20:20:06 [25557] [INFO] 4 workers
2017-10-24 20:20:21 [25557] [INFO] 4 workers
2017-10-24 20:20:36 [25557] [INFO] 4 workers
2017-10-24 20:20:51 [25557] [INFO] 4 workers
2017-10-24 20:21:06 [25557] [INFO] 4 workers
2017-10-24 20:21:21 [25557] [INFO] 4 workers
2017-10-24 20:21:36 [25557] [INFO] 4 workers
2017-10-24 20:21:51 [25557] [INFO] 4 workers
2017-10-24 20:22:06 [25557] [INFO] 4 workers
2017-10-24 20:22:21 [25557] [INFO] 4 workers
2017-10-24 20:22:36 [25557] [INFO] 4 workers
2017-10-24 20:22:51 [25557] [INFO] 4 workers
2017-10-24 20:23:06 [25557] [INFO] 4 workers
2017-10-24 20:23:21 [25557] [INFO] 4 workers
2017-10-24 20:23:36 [25557] [INFO] 4 workers
2017-10-24 20:23:51 [25557] [INFO] 4 workers
2017-10-24 20:24:06 [25557] [INFO] 4 workers
2017-10-24 20:24:21 [25557] [INFO] 4 workers
2017-10-24 20:24:36 [25557] [INFO] 4 workers
2017-10-24 20:24:51 [25557] [INFO] 4 workers
2017-10-24 20:25:06 [25557] [INFO] 4 workers
2017-10-24 20:25:21 [25557] [INFO] 4 workers
2017-10-24 20:25:36 [25557] [INFO] 4 workers
2017-10-24 20:25:51 [25557] [INFO] 4 workers
2017-10-24 20:26:07 [25557] [INFO] 4 workers
2017-10-24 20:26:22 [25557] [INFO] 4 workers
2017-10-24 20:26:37 [25557] [INFO] 4 workers
2017-10-24 20:26:52 [25557] [INFO] 4 workers
2017-10-24 20:27:07 [25557] [INFO] 4 workers
2017-10-24 20:27:22 [25557] [INFO] 4 workers
2017-10-24 20:27:37 [25557] [INFO] 4 workers
2017-10-24 20:27:52 [25557] [INFO] 4 workers
2017-10-24 20:28:07 [25557] [INFO] 4 workers
2017-10-24 20:28:22 [25557] [INFO] 4 workers
2017-10-24 20:28:37 [25557] [INFO] 4 workers
2017-10-24 20:28:52 [25557] [INFO] 4 workers
2017-10-24 20:29:07 [25557] [INFO] 4 workers
2017-10-24 20:29:22 [25557] [INFO] 4 workers
2017-10-24 20:29:37 [25557] [INFO] 4 workers
2017-10-24 20:29:52 [25557] [INFO] 4 workers
2017-10-24 20:30:07 [25557] [INFO] 4 workers
2017-10-24 20:30:22 [25557] [INFO] 4 workers
2017-10-24 20:30:37 [25557] [INFO] 4 workers
2017-10-24 20:30:52 [25557] [INFO] 4 workers
2017-10-24 20:31:07 [25557] [INFO] 4 workers
2017-10-24 20:31:22 [25557] [INFO] 4 workers
2017-10-24 20:31:37 [25557] [INFO] 4 workers
2017-10-24 20:31:52 [25557] [INFO] 4 workers
2017-10-24 20:32:07 [25557] [INFO] 4 workers
2017-10-24 20:32:22 [25557] [INFO] 4 workers
2017-10-24 20:32:37 [25557] [INFO] 4 workers
2017-10-24 20:32:52 [25557] [INFO] 4 workers
2017-10-24 20:33:07 [25557] [INFO] 4 workers
2017-10-24 20:33:22 [25557] [INFO] 4 workers
2017-10-24 20:33:37 [25557] [INFO] 4 workers
2017-10-24 20:33:52 [25557] [INFO] 4 workers
2017-10-24 20:34:07 [25557] [INFO] 4 workers
2017-10-24 20:34:22 [25557] [INFO] 4 workers
2017-10-24 20:34:37 [25557] [INFO] 4 workers
2017-10-24 20:34:52 [25557] [INFO] 4 workers
2017-10-24 20:35:07 [25557] [INFO] 4 workers
2017-10-24 20:35:22 [25557] [INFO] 4 workers
2017-10-24 20:35:37 [25557] [INFO] 4 workers
2017-10-24 20:35:52 [25557] [INFO] 4 workers
2017-10-24 20:36:07 [25557] [INFO] 4 workers
2017-10-24 20:36:22 [25557] [INFO] 4 workers
2017-10-24 20:36:37 [25557] [INFO] 4 workers
2017-10-24 20:36:52 [25557] [INFO] 4 workers
2017-10-24 20:37:07 [25557] [INFO] 4 workers
2017-10-24 20:37:22 [25557] [INFO] 4 workers
2017-10-24 20:37:37 [25557] [INFO] 4 workers
2017-10-24 20:37:52 [25557] [INFO] 4 workers
2017-10-24 20:38:07 [25557] [INFO] 4 workers
2017-10-24 20:38:22 [25557] [INFO] 4 workers
2017-10-24 20:38:37 [25557] [INFO] 4 workers
2017-10-24 20:38:52 [25557] [INFO] 4 workers
2017-10-24 20:39:07 [25557] [INFO] 4 workers
2017-10-24 20:39:22 [25557] [INFO] 4 workers
2017-10-24 20:39:37 [25557] [INFO] 4 workers
2017-10-24 20:39:52 [25557] [INFO] 4 workers
2017-10-24 20:40:07 [25557] [INFO] 4 workers
2017-10-24 20:40:22 [25557] [INFO] 4 workers
2017-10-24 20:40:37 [25557] [INFO] 4 workers
2017-10-24 20:40:52 [25557] [INFO] 4 workers
2017-10-24 20:41:07 [25557] [INFO] 4 workers
2017-10-24 20:41:22 [25557] [INFO] 4 workers
2017-10-24 20:41:37 [25557] [INFO] 4 workers
2017-10-24 20:41:52 [25557] [INFO] 4 workers
2017-10-24 20:42:07 [25557] [INFO] 4 workers
2017-10-24 20:42:22 [25557] [INFO] 4 workers
2017-10-24 20:42:37 [25557] [INFO] 4 workers
2017-10-24 20:42:52 [25557] [INFO] 4 workers
2017-10-24 20:43:07 [25557] [INFO] 4 workers
2017-10-24 20:43:22 [25557] [INFO] 4 workers
2017-10-24 20:43:37 [25557] [INFO] 4 workers
2017-10-24 20:43:52 [25557] [INFO] 4 workers
2017-10-24 20:44:07 [25557] [INFO] 4 workers
2017-10-24 20:44:22 [25557] [INFO] 4 workers
2017-10-24 20:44:37 [25557] [INFO] 4 workers
2017-10-24 20:44:52 [25557] [INFO] 4 workers
2017-10-24 20:45:07 [25557] [INFO] 4 workers
2017-10-24 20:45:22 [25557] [INFO] 4 workers
2017-10-24 20:45:37 [25557] [INFO] 4 workers
2017-10-24 20:45:52 [25557] [INFO] 4 workers
2017-10-24 20:46:07 [25557] [INFO] 4 workers
2017-10-24 20:46:22 [25557] [INFO] 4 workers
2017-10-24 20:46:37 [25557] [INFO] 4 workers
2017-10-24 20:46:52 [25557] [INFO] 4 workers
2017-10-24 20:47:07 [25557] [INFO] 4 workers
2017-10-24 20:47:23 [25557] [INFO] 4 workers
2017-10-24 20:47:37 [25557] [INFO] 4 workers
2017-10-24 20:47:53 [25557] [INFO] 4 workers
2017-10-24 20:48:08 [25557] [INFO] 4 workers
2017-10-24 20:48:23 [25557] [INFO] 4 workers
2017-10-24 20:48:38 [25557] [INFO] 4 workers
2017-10-24 20:48:53 [25557] [INFO] 4 workers
2017-10-24 20:49:08 [25557] [INFO] 4 workers
2017-10-24 20:49:23 [25557] [INFO] 4 workers
2017-10-24 20:49:38 [25557] [INFO] 4 workers
2017-10-24 20:49:53 [25557] [INFO] 4 workers
2017-10-24 20:50:08 [25557] [INFO] 4 workers
2017-10-24 20:50:23 [25557] [INFO] 4 workers
2017-10-24 20:50:38 [25557] [INFO] 4 workers
2017-10-24 20:50:53 [25557] [INFO] 4 workers
2017-10-24 20:51:08 [25557] [INFO] 4 workers
2017-10-24 20:51:23 [25557] [INFO] 4 workers
2017-10-24 20:51:38 [25557] [INFO] 4 workers
2017-10-24 20:51:53 [25557] [INFO] 4 workers
2017-10-24 20:52:08 [25557] [INFO] 4 workers
2017-10-24 20:52:23 [25557] [INFO] 4 workers
2017-10-24 20:52:38 [25557] [INFO] 4 workers
2017-10-24 20:52:53 [25557] [INFO] 4 workers
2017-10-24 20:53:08 [25557] [INFO] 4 workers
2017-10-24 20:53:23 [25557] [INFO] 4 workers
2017-10-24 20:53:38 [25557] [INFO] 4 workers
2017-10-24 20:53:53 [25557] [INFO] 4 workers
2017-10-24 20:54:08 [25557] [INFO] 4 workers
2017-10-24 20:54:23 [25557] [INFO] 4 workers
2017-10-24 20:54:38 [25557] [INFO] 4 workers
2017-10-24 20:54:53 [25557] [INFO] 4 workers
2017-10-24 20:55:08 [25557] [INFO] 4 workers
2017-10-24 20:55:23 [25557] [INFO] 4 workers
2017-10-24 20:55:38 [25557] [INFO] 4 workers
2017-10-24 20:55:53 [25557] [INFO] 4 workers
2017-10-24 20:56:08 [25557] [INFO] 4 workers
2017-10-24 20:56:23 [25557] [INFO] 4 workers
2017-10-24 20:56:38 [25557] [INFO] 4 workers
2017-10-24 20:56:53 [25557] [INFO] 4 workers
2017-10-24 20:57:08 [25557] [INFO] 4 workers
2017-10-24 20:57:23 [25557] [INFO] 4 workers
2017-10-24 20:57:38 [25557] [INFO] 4 workers
2017-10-24 20:57:53 [25557] [INFO] 4 workers
2017-10-24 20:58:08 [25557] [INFO] 4 workers
2017-10-24 20:58:23 [25557] [INFO] 4 workers
2017-10-24 20:58:38 [25557] [INFO] 4 workers
2017-10-24 20:58:53 [25557] [INFO] 4 workers
2017-10-24 20:59:08 [25557] [INFO] 4 workers
2017-10-24 20:59:23 [25557] [INFO] 4 workers
2017-10-24 20:59:38 [25557] [INFO] 4 workers
2017-10-24 20:59:53 [25557] [INFO] 4 workers
2017-10-24 21:00:08 [25557] [INFO] 4 workers
2017-10-24 21:00:23 [25557] [INFO] 4 workers
2017-10-24 21:00:38 [25557] [INFO] 4 workers
2017-10-24 21:00:53 [25557] [INFO] 4 workers
2017-10-24 21:01:08 [25557] [INFO] 4 workers
2017-10-24 21:01:23 [25557] [INFO] 4 workers
2017-10-24 21:01:38 [25557] [INFO] 4 workers
2017-10-24 21:01:53 [25557] [INFO] 4 workers
2017-10-24 21:02:08 [25557] [INFO] 4 workers
2017-10-24 21:02:23 [25557] [INFO] 4 workers
2017-10-24 21:02:38 [25557] [INFO] 4 workers
2017-10-24 21:02:53 [25557] [INFO] 4 workers
2017-10-24 21:03:08 [25557] [INFO] 4 workers
2017-10-24 21:03:23 [25557] [INFO] 4 workers
2017-10-24 21:03:38 [25557] [INFO] 4 workers
2017-10-24 21:03:53 [25557] [INFO] 4 workers
2017-10-24 21:04:08 [25557] [INFO] 4 workers
2017-10-24 21:04:23 [25557] [INFO] 4 workers
2017-10-24 21:04:38 [25557] [INFO] 4 workers
2017-10-24 21:04:53 [25557] [INFO] 4 workers
2017-10-24 21:05:08 [25557] [INFO] 4 workers
2017-10-24 21:05:38 [25557] [INFO] 4 workers
2017-10-24 21:05:53 [25557] [INFO] 4 workers
2017-10-24 21:06:08 [25557] [INFO] 4 workers
2017-10-24 21:06:23 [25557] [INFO] 4 workers
2017-10-24 21:06:38 [25557] [INFO] 4 workers
2017-10-24 21:06:53 [25557] [INFO] 4 workers
2017-10-24 21:07:08 [25557] [INFO] 4 workers
2017-10-24 21:07:23 [25557] [INFO] 4 workers
2017-10-24 21:07:38 [25557] [INFO] 4 workers
2017-10-24 21:07:53 [25557] [INFO] 4 workers
2017-10-24 21:08:08 [25557] [INFO] 4 workers
2017-10-24 21:08:23 [25557] [INFO] 4 workers
2017-10-24 21:08:38 [25557] [INFO] 4 workers
2017-10-24 21:08:53 [25557] [INFO] 4 workers
2017-10-24 21:09:08 [25557] [INFO] 4 workers
2017-10-24 21:09:23 [25557] [INFO] 4 workers
2017-10-24 21:09:38 [25557] [INFO] 4 workers
2017-10-24 21:09:53 [25557] [INFO] 4 workers
2017-10-24 21:10:08 [25557] [INFO] 4 workers
2017-10-24 21:10:23 [25557] [INFO] 4 workers
2017-10-24 21:10:38 [25557] [INFO] 4 workers
2017-10-24 21:10:53 [25557] [INFO] 4 workers
2017-10-24 21:11:08 [25557] [INFO] 4 workers
2017-10-24 21:11:23 [25557] [INFO] 4 workers
2017-10-24 21:11:38 [25557] [INFO] 4 workers
2017-10-24 21:11:53 [25557] [INFO] 4 workers
2017-10-24 21:12:08 [25557] [INFO] 4 workers
2017-10-24 21:12:23 [25557] [INFO] 4 workers
2017-10-24 21:12:39 [25557] [INFO] 4 workers
2017-10-24 21:12:54 [25557] [INFO] 4 workers
2017-10-24 21:13:09 [25557] [INFO] 4 workers
2017-10-24 21:13:24 [25557] [INFO] 4 workers
2017-10-24 21:13:39 [25557] [INFO] 4 workers
2017-10-24 21:13:54 [25557] [INFO] 4 workers
2017-10-24 21:14:09 [25557] [INFO] 4 workers
2017-10-24 21:14:24 [25557] [INFO] 4 workers
2017-10-24 21:14:39 [25557] [INFO] 4 workers
2017-10-24 21:14:54 [25557] [INFO] 4 workers
2017-10-24 21:15:09 [25557] [INFO] 4 workers
2017-10-24 21:15:24 [25557] [INFO] 4 workers
2017-10-24 21:15:39 [25557] [INFO] 4 workers
2017-10-24 21:15:54 [25557] [INFO] 4 workers
2017-10-24 21:16:09 [25557] [INFO] 4 workers
2017-10-24 21:16:24 [25557] [INFO] 4 workers
2017-10-24 21:16:39 [25557] [INFO] 4 workers
2017-10-24 21:16:54 [25557] [INFO] 4 workers
2017-10-24 21:17:09 [25557] [INFO] 4 workers
2017-10-24 21:17:24 [25557] [INFO] 4 workers
2017-10-24 21:17:39 [25557] [INFO] 4 workers
2017-10-24 21:17:54 [25557] [INFO] 4 workers
2017-10-24 21:18:09 [25557] [INFO] 4 workers
2017-10-24 21:18:24 [25557] [INFO] 4 workers
2017-10-24 21:18:39 [25557] [INFO] 4 workers
2017-10-24 21:18:54 [25557] [INFO] 4 workers
2017-10-24 21:19:09 [25557] [INFO] 4 workers
2017-10-24 21:19:24 [25557] [INFO] 4 workers
2017-10-24 21:19:39 [25557] [INFO] 4 workers
2017-10-24 21:19:54 [25557] [INFO] 4 workers
2017-10-24 21:20:09 [25557] [INFO] 4 workers
2017-10-24 21:20:24 [25557] [INFO] 4 workers
2017-10-24 21:20:39 [25557] [INFO] 4 workers
2017-10-24 21:20:54 [25557] [INFO] 4 workers
2017-10-24 21:21:09 [25557] [INFO] 4 workers
2017-10-24 21:21:24 [25557] [INFO] 4 workers
2017-10-24 21:21:39 [25557] [INFO] 4 workers
2017-10-24 21:21:54 [25557] [INFO] 4 workers
2017-10-24 21:22:09 [25557] [INFO] 4 workers
2017-10-24 21:22:24 [25557] [INFO] 4 workers
2017-10-24 21:22:39 [25557] [INFO] 4 workers
2017-10-24 21:22:54 [25557] [INFO] 4 workers
2017-10-24 21:23:09 [25557] [INFO] 4 workers
2017-10-24 21:23:24 [25557] [INFO] 4 workers
2017-10-24 21:23:39 [25557] [INFO] 4 workers
2017-10-24 21:23:54 [25557] [INFO] 4 workers
2017-10-24 21:24:09 [25557] [INFO] 4 workers
2017-10-24 21:24:24 [25557] [INFO] 4 workers
2017-10-24 21:24:39 [25557] [INFO] 4 workers
2017-10-24 21:24:54 [25557] [INFO] 4 workers
2017-10-24 21:25:09 [25557] [INFO] 4 workers
2017-10-24 21:25:24 [25557] [INFO] 4 workers
2017-10-24 21:25:39 [25557] [INFO] 4 workers
2017-10-24 21:25:54 [25557] [INFO] 4 workers
2017-10-24 21:26:09 [25557] [INFO] 4 workers
2017-10-24 21:26:24 [25557] [INFO] 4 workers
2017-10-24 21:26:39 [25557] [INFO] 4 workers
2017-10-24 21:26:54 [25557] [INFO] 4 workers
2017-10-24 21:27:09 [25557] [INFO] 4 workers
2017-10-24 21:27:24 [25557] [INFO] 4 workers
2017-10-24 21:27:39 [25557] [INFO] 4 workers
2017-10-24 21:27:54 [25557] [INFO] 4 workers
2017-10-24 21:28:09 [25557] [INFO] 4 workers
2017-10-24 21:28:24 [25557] [INFO] 4 workers
2017-10-24 21:28:39 [25557] [INFO] 4 workers
2017-10-24 21:28:54 [25557] [INFO] 4 workers
2017-10-24 21:29:09 [25557] [INFO] 4 workers
2017-10-24 21:29:11 [25563] [INFO] Worker exiting (pid: 25563)
2017-10-24 21:29:11 [25561] [INFO] Worker exiting (pid: 25561)
2017-10-24 21:29:11 [25560] [INFO] Worker exiting (pid: 25560)
2017-10-24 21:29:11 [25557] [INFO] 4 workers
2017-10-24 21:29:11 [25557] [INFO] Handling signal: int
2017-10-24 21:29:11 [25562] [INFO] Worker exiting (pid: 25562)
2017-10-24 21:29:11 [25557] [INFO] Shutting down: Master
